/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// KubevirtBootstrapNetworkConfigApplyConfiguration represents a declarative configuration of the KubevirtBootstrapNetworkConfig type for use
// with apply.
type KubevirtBootstrapNetworkConfigApplyConfiguration struct {
	Network     *string  `json:"network,omitempty"`
	Interface   *string  `json:"interface,omitempty"`
	Addresses   []string `json:"addresses,omitempty"`
	Nameservers []string `json:"nameservers,omitempty"`
	Gateway     []string `json:"gateway,omitempty"`
}

// KubevirtBootstrapNetworkConfigApplyConfiguration constructs a declarative configuration of the KubevirtBootstrapNetworkConfig type for use with
// apply.
func KubevirtBootstrapNetworkConfig() *KubevirtBootstrapNetworkConfigApplyConfiguration {
	return &KubevirtBootstrapNetworkConfigApplyConfiguration{}
}

// WithNetwork sets the Network field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Network field is set to the value of the last call.
func (b *KubevirtBootstrapNetworkConfigApplyConfiguration) WithNetwork(value string) *KubevirtBootstrapNetworkConfigApplyConfiguration {
	b.Network = &value
	return b
}

// WithInterface sets the Interface field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interface field is set to the value of the last call.
func (b *KubevirtBootstrapNetworkConfigApplyConfiguration) WithInterface(value string) *KubevirtBootstrapNetworkConfigApplyConfiguration {
	b.Interface = &value
	return b
}

// WithAddresses adds the given value to the Addresses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Addresses field.
func (b *KubevirtBootstrapNetworkConfigApplyConfiguration) WithAddresses(values ...string) *KubevirtBootstrapNetworkConfigApplyConfiguration {
	for i := range values {
		b.Addresses = append(b.Addresses, values[i])
	}
	return b
}

// WithNameservers adds the given value to the Nameservers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Nameservers field.
func (b *KubevirtBootstrapNetworkConfigApplyConfiguration) WithNameservers(values ...string) *KubevirtBootstrapNetworkConfigApplyConfiguration {
	for i := range values {
		b.Nameservers = append(b.Nameservers, values[i])
	}
	return b
}

// WithGateway adds the given value to the Gateway field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Gateway field.
func (b *KubevirtBootstrapNetworkConfigApplyConfiguration) WithGateway(values ...string) *KubevirtBootstrapNetworkConfigApplyConfiguration {
	for i := range values {
		b.Gateway = append(b.Gateway, values[i])
	}
	return b
}
